Remove duplicate methods
Fixes:
./chirp/drivers/icx90.py:670:5: F811 redefinition of unused 'get_raw_memory' from line 605
./chirp/drivers/ft1d.py:2528:5: F811 redefinition of unused 'apply_WEhemi' from line 2521