Remove duplicate imports
Fixes:
./chirp/drivers/retevis_rt98.py:25:1: F811 redefinition of unused 'RadioSettingValueString' from line 25
./chirp/drivers/th9000.py:25:1: F811 redefinition of unused 'RadioSettingValueString' from line 25
./chirp/drivers/icf.py:25:1: F811 redefinition of unused 'struct' from line 21
./chirp/drivers/icf.py:31:1: F811 redefinition of unused 'util' from line 27